Hicham
jariketting/gride pull request #56
Opened 2019-12-25 16:25 UTC by Hicham010

Het is nu mogelijk om tijdens de employee edit een skill, location of function toe te voegen.

2019-12-25 16:31 UTC, Hicham010 commented
Het zelfde is nu ook mogelijk bij het maken van een nieuwe employee.

2020-01-06 09:46 UTC, guusjoppe requested changes
Redirect naar Skills/Create ipv Skills

2020-01-06 11:02 UTC, guusjoppe requested changes
FeedbackController en Model doen nu toch nog niets? Kan je die er uit laten?

2020-01-06 11:12 UTC, JulesImmerzeel approved these changes
ok

2020-01-06 11:13 UTC, guusjoppe approved these changes

2020-01-06 11:13 UTC, merged